name: sheep_env
channels:
  #- anaconda
  - conda-forge
  #- defaults
dependencies:
  - cudatoolkit
  - cudnn
  - opencv
  - numpy
  - matplotlib
  - pandas
  - tensorflow-gpu==1.15
  - keras-gpu
  - blas
  - tqdm
  - h5py==2.10.0
  #- pip
  #- pip:
  #    - tqdm
  # - scikit-image
