name: sheep_env
channels:
  #- anaconda
  - conda-forge
  #- defaults
dependencies:
  - opencv
  - numpy
  - matplotlib
  - pandas
  - tensorflow-gpu==1.13.1
  - keras
  - tqdm
  #- pip
  #- pip:
  #    - tqdm
  # - scikit-image
